dist: trusty
sudo: required
language: cpp
compiler: clang

before-install: 
  - sudo apt-get update

install: 
  - sudo apt-get install libev-dev libgoogle-perftools-dev libhiredis-dev libicu-dev libcurl4-openssl-dev libboost-dev libluajit-5.1-dev libpth-dev uuid-dev
  
  # Get libjansson version 2.5, the one in Ubuntu 12.04's repos is way outdated.
  - cd ~/build
  - wget http://www.digip.org/jansson/releases/jansson-2.9.tar.gz
  - tar xvzf jansson-2.9.tar.gz
  - cd jansson-2.9
  - ./configure --prefix=/usr/ && make && sudo make install
  
  # We need to get and build libglog because Ubuntu 12.04 doesn't have that in its repos.
  - cd ~/build
  - wget https://github.com/google/glog/archive/v0.3.4.tar.gz
  - tar xvzf v0.3.4.tar.gz
  - cd glog-0.3.4
  - ./configure && make && sudo make install
  
  # Fetch and build evHTTPClient
  - cd ~/build
  - git clone https://github.com/zwagoth/evhttpclient
  - cd evhttpclient
  - make
  - sudo cp *.h /usr/include
  - sudo cp libevhttpclient.so /usr/lib
  
script: 
  # Finally, build fserv.
  - cd ~/build/f-list/fserv
  - make all
